### ISSUE TITLE
3.1.2-1 - Failed dependencies libpki 0.9.0

### ISSUE THREAD

**Issue by n8v8R** [openca/openca-ocspd#43]
Trying to install openca-ocspd-3.1.2-1.el7.x86_64.rpm and ending up with:

error: Failed dependencies:
        libpki >= 0.9.0 is needed by openca-ocspd-3.1.2-1.el7.x86_64

Yet there is no libpki 0.9.0 available on SF for download...? Posted it JUL 06 to the openca-ocspd mailing list but never got a response.

**Comment by herste** [comment]
Any updates on this?

**Comment by n8v8R** [comment]
@herste I wrote to the corresponding mailing list and an email to the maintainer listed at https://www.openca.org/projects/libpki/contacts.shtml and neither yielded a response, same as this ticket

**Comment by opencrypto** [comment]
Hi herste, n8v8R,

There are no packages (RPMs), but you can easily create them by using:

  $ ./configure && make rpm

Make sure the openssl-devel openldap-devel and finger packages are installed. I also just built the packages for el7 and should be available soon-ish in the download section:

  https://www.openca.org/projects/libpki/downloads.shtml

You can find the LibPKI Repository:

  https://github.com/openca/libpki

**Comment by n8v8R** [comment]
@opencrypto having installed `libpki-0.9.0-1.el7.x86_64.rpm` and thereafter trying to installing `openca-ocspd-3.1.2-1.el7.x86_64.rpm` throwing this error

> --> Running transaction check
> ---> Package openca-ocspd.x86_64 0:3.1.2-1.el7 will be installed
> --> Processing Dependency: libpki.so.89()(64bit) for package: openca-ocspd-3.1.2-1.el7.x86_64
> Error: Package: openca-ocspd-3.1.2-1.el7.x86_64 (/openca-ocspd-3.1.2-1.el7.x86_64)
>            Requires: libpki.so.**89**()(64bit)
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
