### ISSUE TITLE
[ERROR] CRL Validity Check FAILED (Missing lastUpdate)

### ISSUE THREAD

**Issue by gvandenbosch** [openca/openca-ocspd#48]
OCSPD v3.1.2

I am trying to integrate my own PKI with the OCSP responder.

When I am starting the daemon I receive errors that `lastUpdate` field is missing:

`Sep 10 12:59:15 2019 GMT [82155] INFO: CRL signature is verified [Code: 1, CA Subject: O=emfytech, OU=engineering, CN=gerard.home_IssuingCA, L=kuantan, ST=pahang, C=MY]`
`Sep 10 12:59:15 2019 GMT [82155] INFO: [config.c:854] [DEBUG] CRL Signature verified successfully [URL: /bxs/pki/ca/crl/crl_gerard.home_IssuingCA.pem]`
`Sep 10 12:59:15 2019 GMT [82155] ERROR: [crl.c:286] [ERROR] CRL Validity Check FAILED (Missing lastUpdate) [CA: gerard.home_ocsp_ica, Error: no lastUpdate Field, Code: 5]`
`Sep 10 12:59:15 2019 GMT [82155] ERROR: [config.c:873] [ERROR] CRL Validity check FAILED [CA: gerard.home_ocsp_ica, Code: 5]`

However when I check the CRL with openssl the lastUpdate field seems to be there.

`openssl crl -inform PEM -lastupdate -noout -in  /bxs/pki/ca/crl/crl_gerard.home_IssuingCA.pem`
`lastUpdate=Sep 10 14:59:12 2019 GMT`

What could be the issue here?

**Comment by mrbaseman** [comment]
hmm... could it be that something in the logic around https://github.com/openca/openca-ocspd/blob/master/src/ocspd/crl.c#L274 is not correct and the crl just was not valid yet and it should have triggered the other branch of the error handling there? Could you try again?

Your lastUpdate was yesterday afternoon but you have opened this issue yesterday morning, so if you check the same file today it might work - but still the error message would have been the wrong one.

**Comment by gvandenbosch** [comment]
Indeed was the time issue, I just realised my system is in the wrong timezone and therefore the time was in the future.

It works now, thank you for the help.

**Comment by mrbaseman** [comment]
@gvandenbosch correct time settings are crucial for handling certificates and crls. 

Anyhow, you should have received the following error in this case:
`CRL Validity Check FAILED [CA: %s, Error: Not Valid Yet, Code: %d]`

@opencrypto I think instead of `if (i == 0){` it should read `if (i > 0) {` here: https://github.com/openca/openca-ocspd/blob/master/src/ocspd/crl.c#L274
